### ISSUE TITLE
MAJOR: Find an alternative for Remoto

### ISSUE THREAD

**Issue by thorwald** [jumpstarter-io/jsc#20]
Remoto and execnet leaves a lot of wishes unanswered for us. Here's a list
1. No MS Windows support
2. Print outputs aren't flushed before function return is put in queue
3. No support for **kwargs and tuples which forces us to do a workaround with decorators
4. ctrl+c will kill the ssh connection so we can't use ^C properly
5. (minor) can't set ssh port.

**Comment by cajlarsson** [comment]
We can steal the concept of remoto, reimplement and build in our current wrapper functionality  using paramiko instead of execnet. Would be a kickass lib

**Comment by thorwald** [comment]
fixed in v2.0
