### ISSUE TITLE
Show what command is run when using run command

### ISSUE THREAD

**Issue by StefanNyman** [jumpstarter-io/jsc#25]
currently no output. would be nice if "run /app/code/asdf.sh" results in printout of "/app/code/asdf.sh"

**Comment by hnsl** [comment]
It's documented to run /app/code/init, which was the purpose of this function. Not to run arbitrary scripts. This is what ssh is for. ;)

Would close with no fix but it's a legitimate UX problem that the command does not indicate what is run or shows helpful error when it can't start /app/code/init.

**Comment by cajlarsson** [comment]
I'm pretty sure he means the recipe-command run and not the jsc-command run

**Comment by StefanNyman** [comment]
yep. sorry. recipe run command.
